### ISSUE TITLE
Apartado de contacto

### ISSUE THREAD

**Issue by ImZeusNC** [ImZeusNC/paginaDiscord#2]
Falta rellenar esta pagina que actualmente se encuentra vacia, por tanto, debe incluir:
- contacto del admin del servidor
- contacto del staff

**Comment by C0nej01** [comment]
intentare cumplir esto :3

**Comment by C0nej01** [comment]
El apartado de Contacto ha sido estructurado, solo falta añadir los datos y enlaces necesarios
